### ISSUE TITLE
Data structure template 

### ISSUE THREAD

**Issue by Frankazo** [Frankazo/JAT-BackEnd#4]
- https://github.com/Frankazo/JAT-FrontEnd/blob/master/src/components/Board/initial-data.js

**Comment by karmanya007** [comment]
What exactly is the job??

**Comment by Frankazo** [comment]
Hi @karmanya007, I need to build the model for the data structure you see there, here is the ERD's: 
---
![ERD](https://i.imgur.com/9egaDPT.png)

**Comment by Frankazo** [comment]
Something like this: https://github.com/Frankazo/come-criollo-api/blob/master/app/models/restaurant.js

**Comment by karmanya007** [comment]
I can try if you want?

**Comment by karmanya007** [comment]
So there will be 
1: User model
2: Job search model
3: Column model
4: Cards model

Could you also specify the relation between them?

**Comment by Frankazo** [comment]
The user has many Job Tables (by reference)
The Job Table has many columns (by subdocument)
The Columns has many Cards (by subdocument)

You can see check out the user model is already defined.

**Comment by karmanya007** [comment]
Okay. Would get on this asap.

**Comment by Frankazo** [comment]
Ticket divided into smaller steps on issues #8 #9 #10
